version: 0.2
phases:
  build:
    commands:
      - pwd && echo "current codebuild directory"
      - cat /codebuild/output/tmp/script.sh
      - cd /tmp
      - pwd && echo "obviously we are in tmp now"
      - mkdir /tmp/folder\ with\ space
      - touch /tmp/folder\ with\ space\somefile.txt
      - cd /tmp/folder\ with\ space
      - ls -lah && echo "expecting this to list somefile.txt"
      - pwd && echo "codebuild has reset the current directory"
      - du -sh * | sort -h
      - df -ha
      - df -ih
      - docker system prune
artifact:
  artifacts:
  files:
    - '**/*'
  base-directory: 's3codepipelinetestdummy'
